# Generated by Django 6.0.6 on 2026-06-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REQUEST_CREATED', 'Request Created'), ('REQUEST_ACCEPTED', 'Request Accepted'), ('REQUEST_REJECTED', 'Request Rejected'), ('REQUEST_CANCELLED', 'Request Cancelled'), ('REQUEST_STARTED', 'Request Started'), ('REQUEST_COMPLETED', 'Request Completed'), ('NEW_REVIEW', 'New Review')], default='something', max_length=50),
            preserve_default=False,
        ),
    ]
