# Generated by Django 6.0.6 on 2026-06-10 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notification_type'),
        ('requests', '0004_alter_servicerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='requests.servicerequest'),
        ),
    ]
