# Generated by Django 6.0.6 on 2026-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REQUEST_CREATED', 'Request Created'), ('REQUEST_ACCEPTED', 'Request Accepted'), ('REQUEST_REJECTED', 'Request Rejected'), ('REQUEST_CANCELLED', 'Request Cancelled'), ('REQUEST_STARTED', 'Request Started'), ('REQUEST_COMPLETED', 'Request Completed'), ('NEW_REVIEW', 'New Review'), ('NEW_MESSAGE', 'New Message')], max_length=50),
        ),
    ]
