# Generated by Django 6.0.6 on 2026-06-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
