# Generated by Django 6.0.6 on 2026-08-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_slug_serviceimage_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(default='Bahir Dar', max_length=150),
            preserve_default=False,
        ),
    ]
