# Generated by Django 6.0.6 on 2026-06-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_servicerequest_address_servicerequest_agreed_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='complete_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='start_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
