# Generated by Django 6.0.6 on 2026-07-28 10:27

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_skill_remove_providerprofile_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerapplication',
            name='government_id_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='government_id'),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='government_id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_provider_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
