# Generated by Django 6.0.6 on 2026-07-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_providerapplication_government_id_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerapplication',
            name='government_id_image',
        ),
        migrations.RemoveField(
            model_name='providerapplication',
            name='government_id_number',
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='identity_provider',
            field=models.CharField(choices=[('manual', 'Manual'), ('fayda', 'Fayda')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='identity_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='identity_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='providerapplication',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
