# Generated by Django 6.0.6 on 2026-07-28 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_providerapplication_government_id_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerapplication',
            name='identity_provider',
        ),
        migrations.RemoveField(
            model_name='providerapplication',
            name='identity_reference',
        ),
        migrations.RemoveField(
            model_name='providerapplication',
            name='identity_status',
        ),
        migrations.RemoveField(
            model_name='providerapplication',
            name='identity_verified_at',
        ),
    ]
